### ISSUE TITLE
error:  net_G = Generator(args, device).to(device)

### ISSUE THREAD

**Issue by molyswu** [Agchai52/ConditinalDeblurGAN-Pytorch#1]
Hi, 
Tried to python main.py --phase train --epoch  
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    train.train(args)
  File "~/Deblur/ConditinalDeblurGAN-Pytorch/train.py", line 36, in train
    net_G = Generator(args, device).to(device)
TypeError: __init__() takes 2 positional arguments but 3 were given
  molyswu

**Comment by molyswu** [comment]
class Generator(nn.Module):
    def __init__(self, args):
to 
class Generator(nn.Module):
    def __init__(self, args，device='cpu'):

ok
